baseURL = "https://moralrights.tech/"
languageCode = "en-us"
title = "Moral Rights"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "learn"

topics = ["Contradiction", "Universal", "Activity"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
enableRobotsTXT = true
publishDir = "public"
googleAnalytics = "UA-115076488-1"
amazonAssociateTrackingId = "mobilea0dbe49-20"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  title = "Moral Rights"
  description = "A technical specification for a foundation of minimal requirements of government"
  editURL = "https://github.com/InTEGr8or/moral-rights/edit/master/content/"
  author = "Mark Stouffer"
  taglines = [
    "A technical specification for",
    "a foundation of minimal",
    "requirements of government"
  ]
  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  version = "beta"
  githubURL = "git@github.com:InTEGr8or/moral-rights.git"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/hogo-theme.css", "css/theme.css"]
